@contentType = application/json 

GET http://localhost:5000/shop_reviews HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ0xJRU5UIiwiaWF0IjoxNjM5ODI2NDU1LCJleHAiOjE2NzEzODQwNTUsImF1ZCI6IjYxYjc1MTJhODNkM2E5OGZmYjFmMThlZSIsImlzcyI6Im1hbm55In0.itrbe9hgNKa9tfl_wtT0j0GEVFJ9NZMG5utYRG4xutA

###review shop
POST http://localhost:5000/shop_reviews HTTP/1.1
Content-Type: {{contentType}}  
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ0xJRU5UIiwiaWF0IjoxNjM5ODI2NDU1LCJleHAiOjE2NzEzODQwNTUsImF1ZCI6IjYxYjc1MTJhODNkM2E5OGZmYjFmMThlZSIsImlzcyI6Im1hbm55In0.itrbe9hgNKa9tfl_wtT0j0GEVFJ9NZMG5utYRG4xutA

{
  "shop": "61ba2b3812efe83200c54fc8",
  "reviewText": "beautiful and clean shop",
  "rating": 5
}

###get shop reviews
GET http://localhost:5000/shop_reviews/shop/61ba2b3812efe83200c54fc8 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ0xJRU5UIiwiaWF0IjoxNjM5ODI2NDU1LCJleHAiOjE2NzEzODQwNTUsImF1ZCI6IjYxYjc1MTJhODNkM2E5OGZmYjFmMThlZSIsImlzcyI6Im1hbm55In0.itrbe9hgNKa9tfl_wtT0j0GEVFJ9NZMG5utYRG4xutA


